version: '3'

services:

  web:
    build: .
    # command: >
    #   bash -c "gunicorn --bind 0.0.0.0:8001 zenylog.wsgi"
    command: gunicorn zenylog.wsgi:application --bind 0.0.0.0:8001
    volumes:
      - .:/Zenylog-Backend/
    ports:
      - "8001:8001"

  nginx:
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "90:90"
    depends_on:
      - web


